# Generated by Django 2.1.7 on 2020-06-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monetary',
            fields=[
                ('primary_key', models.CharField(default='', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('fcode', models.CharField(default='', max_length=16)),
                ('name', models.CharField(default='', max_length=32)),
                ('value', models.CharField(default='', max_length=32)),
                ('score', models.IntegerField()),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('tendency', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
