# Generated by Django 2.1.7 on 2020-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monetary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetary',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monetary',
            name='starting_amount',
            field=models.IntegerField(),
        ),
    ]
