# Generated by Django 2.1.7 on 2020-06-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monetary', '0002_auto_20200610_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monetary',
            old_name='primarys_key',
            new_name='primary_key',
        ),
    ]
