# Generated by Django 2.1.7 on 2020-06-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monetary', '0003_auto_20200610_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetary',
            name='fcode',
            field=models.CharField(default='', max_length=8),
        ),
    ]
